### ISSUE TITLE
dchest/captcha  License?

### ISSUE THREAD

**Issue by holys** [tango-contrib/captcha#1]
https://github.com/dchest/captcha/blob/master/LICENSE

> The above copyright notice and this permission notice shall be included in
> all copies or substantial portions of the Software.

**Comment by huang-aaron** [comment]
cache.NewCache 函数不存在

**Comment by lunny** [comment]
@holys  Codes copyied from beego and I keeped the license information but not directly from https://github.com/dchest/captcha, don't the relation between beego and https://github.com/dchest/captcha
